export default{
    JWT_SECRET:"eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5MDM3NzYxNCwiaWF0IjoxNjkwMzc3NjE0fQ.xKjBRvHp9aGr54kmHQ_HBnk4aZakDLFW5zyk489tRVo",
    S3_ACCESS_KEY:"AKIAVWPSVOF6CKTEJBOR",
    S3_SECRET_ACCESS_KEY:"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",
    BUCKETNAME:"buletin-blog"
}